import React from 'react';

interface ReportLetterheadProps {
  title?: string;
  generatedDate?: string;
  generatedBy?: string;
}

export const ReportLetterhead: React.FC<ReportLetterheadProps> = ({
  title = 'Support Ticket System - Report',
  generatedDate,
  generatedBy,
}) => {
  const today = generatedDate || new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="w-full bg-white text-black border-b-2 border-gray-800 p-8 mb-8 print:mb-4">
      {/* Organization Header */}
      <div className="text-center mb-6 border-b border-gray-400 pb-4">
        <h1 className="text-3xl font-bold text-gray-900">Support Ticket System</h1>
        <p className="text-sm text-gray-700 mt-1">Enterprise Support Management Platform</p>
        <div className="flex justify-center gap-6 mt-3 text-xs text-gray-600">
          <span>📧 support@organization.com</span>
          <span>📞 1-800-SUPPORT</span>
          <span>🌐 www.organization.com</span>
        </div>
      </div>

      {/* Report Details */}
      <div className="grid grid-cols-3 gap-4 text-sm">
        <div>
          <p className="font-semibold text-gray-900">Report Type</p>
          <p className="text-gray-700">{title}</p>
        </div>
        <div className="text-center">
          <p className="font-semibold text-gray-900">Generated Date</p>
          <p className="text-gray-700">{today}</p>
        </div>
        <div className="text-right">
          <p className="font-semibold text-gray-900">Generated By</p>
          <p className="text-gray-700">{generatedBy || 'System'}</p>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-4 pt-4 border-t border-gray-300 text-xs text-gray-600">
        <p>
          This document contains confidential information and is intended solely for the use of the addressee.
          Unauthorized disclosure is prohibited.
        </p>
      </div>
    </div>
  );
};

// Print-friendly version without margins
export const ReportLetterheadPrint: React.FC<ReportLetterheadProps> = (props) => {
  return (
    <div className="hidden" id="report-letterhead-print">
      <ReportLetterhead {...props} />
    </div>
  );
};
